# Those images can unfortunately not be freely distributed for license reasons.
# They were built following this tutorial:
# https://blog.crafteo.io/2024/02/29/my-rust-cross-compilation-journey/
# They have been loaded into the runners' image registry manually.

[target.x86_64-apple-darwin]
image = "x86_64-apple-darwin-cross:local"
# Dockerfile: https://github.com/cross-rs/cross-toolchains/blob/5504d9293334744cf2555286707d9907b89afbfb/docker/Dockerfile.x86_64-apple-darwin-cross

[target.aarch64-apple-darwin]
image = "aarch64-apple-darwin-cross:local"
# Dockerfile: https://github.com/cross-rs/cross-toolchains/blob/5504d9293334744cf2555286707d9907b89afbfb/docker/Dockerfile.aarch64-apple-darwin-cross
